#ifndef FLY_REMAP_MACROS
#define FLY_REMAP_MACROS

#if defined(USE_OPENGL) || defined(USE_OPENGLES)
#if defined(USE_OPENGL)
#include<glad/glad.h>
#else
#include<GLES3/gl32.h>
#endif
// Render State
#define FLY_BLEND				GL_BLEND
#define FLY_FUNC_ADD			GL_FUNC_ADD
#define FLY_SRC_ALPHA			GL_SRC_ALPHA
#define FLY_ONE_MINUS_SRC_ALPHA	GL_ONE_MINUS_SRC_ALPHA
#define FLY_CULL_FACE			GL_CULL_FACE
#define FLY_DEPTH_TEST			GL_DEPTH_TEST
#define FLY_SCISSOR_TEST		GL_SCISSOR_TEST
#define FLY_FRONT_AND_BACK		GL_FRONT_AND_BACK
#define FLY_FILL				GL_FILL
// Texture Locators
#define FLY_TEXTURE_2D	GL_TEXTURE_2D
#define FLY_TEXTURE_3D	GL_TEXTURE_3D
#define FLY_TEXTURE0	GL_TEXTURE0
// Draw Mode
#define FLY_STATIC_DRAW		GL_STATIC_DRAW
#define FLY_STREAM_DRAW		GL_STREAM_DRAW
#define FLY_DYNAMIC_DRAW	GL_DYNAMIC_DRAW
#define FLY_TRIANLGES		GL_TRIANGLES
#define FLY_QUADS			GL_QUADS
#define FLY_LINES			GL_LINES
#define FLY_POINTS			GL_POINTS
// Data Types
#define FLY_BYTE    GL_BYTE
#define FLY_UBYTE   GL_UNSIGNED_BYTE
#define FLY_USHORT  GL_UNSIGNED_SHORT
#define FLY_UINT    GL_UNSIGNED_INT
#define FLY_INT     GL_INT
#define FLY_FLOAT   GL_FLOAT
#define FLY_DOUBLE  GL_DOUBLE
// Texture Types
#define FLY_RGBA    GL_RGBA
#define FLY_R8      GL_R8
#define FLY_R16     GL_R16
#define FLY_RGB     GL_RGB
// Texture Parameters
#define FLY_NEAREST         GL_NEAREST
#define FLY_LINEAR          GL_LINEAR
#define FLY_NEAREST_NEAREST GL_NEAREST_MIPMAP_NEAREST
#define FLY_LINEAR_NEAREST  GL_LINEAR_MIPMAP_NEAREST
#define FLY_NEAREST_LINEAR  GL_NEAREST_MIPMAP_LINEAR
#define FLY_LINEAR_LINEAR   GL_LINEAR_MIPMAP_LINEAR
#define FLY_CLAMP           GL_CLAMP_TO_EDGE
#define FLY_MIRROR          GL_MIRRORED_REPEAT
#define FLY_REPEAT          GL_REPEAT
// Shaders
#define FLY_VERTEX_SHADER   GL_VERTEX_SHADER
#define FLY_FRAGMENT_SHADER GL_FRAGMENT_SHADER
#define FLY_COMPUTE_SHADER
#define FLY_GEOMETRY_SHADER
#endif

#endif